language: android
android:
  components:
    - build-tools-23.0.1
    - android-22
    - extra
    - sys-img-x86-android-22
  before_script:
    - echo no | android create avd --force -n test -t android-22 --abi x86
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator