language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-22
    - extra
    - sys-img-x86-android-22
before_script:
  - echo no | android create avd --force -n test -t android-22 --abi x86
  - emulator -avd test -no-audio -no-window &
script:
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - adb devices
  - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace
after_failure:
  - wget http://imgur.com/tools/imgurbash.sh
  - chmod a+x imgurbash.sh
  - adb shell screencap -p | sed 's/\r$//' &gt; screen.png
  - ./imgurbash.sh screen.png